<?php
/**
 * Copyright (c) 2023 by https://github.com/annysmolyan
 *
 * This module provides a visual search functionality for an e-commerce store.
 * For license details, please view the GNU General Public License v3 (GPL 3.0)
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/** Show the visual search popup form */
?>

<?php

use BelSmol\VisualSearch\ViewModel\SearchFormViewModel;
use Magento\Framework\View\Element\Template;

/** @var Template $block  */
/** @var SearchFormViewModel $viewModel */

$viewModel = $block->getData('viewModel');
?>

<div id="visual-search-popup" class="visual-search-popup" style="display: none;" data-bind="scope:'visualSearchPopup'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
                {
                    "#visual-search-popup": {
                        "Magento_Ui/js/core/app": {
                           "components": {
                                "visualSearchPopup": {
                                    "component": "BelSmol_VisualSearch/js/components/visual-search/popup-form",
                                    "isCategorySelectorVisible": <?= /* @noEscape */ (int)$viewModel->canShowCategorySelector(); ?>
                                }
                            }
                        }
                    }
                }
        </script>
</div>
