from flask import Flask, request, jsonify
from FeatureExtractor import FeatureExtractor

app = Flask(__name__)

# Read csv file generated by magento
# and save image vectors
@app.route('/feature-extract/csv-source', methods=['POST'])
def extractFromCsv():
    try:
        data = request.get_json()
        modelName = data['modelName']
        csvFileName = data['csvFileName']

        extractor = FeatureExtractor(modelName)
        extractor.extractFromCsv(csvFileName)
    except Exception as e:
        error_message = str(e)
        response = {
            "error": error_message
        }
        return jsonify(response), 500

    return '', 200


# Extract image vector by given path
# Where imagePath without slash at the beginning.
# e.g. 'catalog/product/m/b/mb01-blue-0.jpg'
@app.route('/feature-extract/path-source', methods=['POST'])
def extractFromImagePath():
    try:
        data = request.get_json()
        modelName = data['modelName']
        imagePath = data['path']

        extractor = FeatureExtractor(modelName)
        vector = extractor.extractFromImagePath(imagePath)
    except Exception as e:
        error_message = str(e)
        response = {
            "error": error_message
        }
        return jsonify(response), 500

    response = {
        "vector": vector
    }

    return jsonify(response), 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
