import pandas as pd
import json
from FeatureModel.InceptionV3 import InceptionV3FeatureExtractor


# Extract image feature for specific CNN model
class FeatureExtractor:
    # Constants for csv field names
    ROW_IMAGE_PATH = 'image_pub_media_path'
    ROW_VECTOR = 'vector'

    MAGENTO_MEDIA_FOLDER = '/magento_media/'
    MAGENTO_CSV_FOLDER = '/magento_csv/'

    def __init__(self, modelName):
        self.model = self._get_feature_extractor_model(modelName)

    # Private method: use in construct only
    def _get_feature_extractor_model(self, model_name):
        if model_name == InceptionV3FeatureExtractor.MODEL_CODE:
            model = InceptionV3FeatureExtractor()
            return model
        else:
            raise Exception("Undefined CNN model name")

    # Public method: Extract images vectors from csv file
    # Read csv file generated by magento
    # and save image vectors
    #
    # Where:
    # csvFileName - csv file name from Magento 'var/visual_search' directory
    def extractFromCsv(self, csvFileName):
        csvFile = self.MAGENTO_CSV_FOLDER + csvFileName
        df = pd.read_csv(csvFile)

        for index, row in df.iterrows():
            try:
                vector = self.extractFromImagePath(row[self.ROW_IMAGE_PATH])  # get image vector
                vectorJson = json.dumps(vector)  # Convert the vector to JSON
                df.at[index, self.ROW_VECTOR] = vectorJson  # Update the 'vector' column with the flattened vector
            except Exception as exception:
                exceptionJson = json.dumps(str(exception))
                df.at[index, self.ROW_VECTOR] = exceptionJson

        df.to_csv(csvFile, index=False)

    # Public method: Extract image vector by given path
    # in magento "pub/media" directory
    #
    # Where:
    # imagePathInPubMedia - image path in Magento "pub/media" directory, without slash at the beginning.
    # e.g. 'catalog/product/m/b/mb01-blue-0.jpg'
    def extractFromImagePath(self, imagePathInPubMedia):
        imageAbsolutePath = self.MAGENTO_MEDIA_FOLDER + imagePathInPubMedia
        vector = self.model.getImageFeature(imageAbsolutePath)  # get image vector
        return vector.tolist()
